import "./globals.css";
import type { Metadata } from "next";
import { Rubik } from "next/font/google";

import React from "react";

const rubik = Rubik({ subsets: ["latin"] });

export const dynamic = 'force-dynamic'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <React.StrictMode>
        <body className={rubik.className}>
          {children}
        </body>
      </React.StrictMode>
    </html>
  );
}
